version: '2'
services:
  name:
    build: .
    restart: no # required to avoid container restarting indefinitely
    labels:
      io.balena.features.balena-api: 1 # required to use the balena API
    environment:
      CATEGORY: animals # if not specified will default to season
      URL: 'https://url-to-your-file/noun.txt,https://url-to-your-file/adj.txt' # formatted for noun.txt, adj.txt
      DEBUG: name # not required unless debugging
